### PR TITLE
Updated dependencies to newer version and added options search

### PR DESCRIPTION
**Pull request by ecigar13**
Hello Garth,

My email: khoanguyen0791@gmail.com 

Thanks a lot for writing the first version. It helped me a lot in fixing streaming and options search in Java. I use this to get data for personal purpose. 

You can see what I did in README.md in my fork. A few main things:
- Updated dependencies to newer version. Their methods changes.
- Updated XSD schema (ally's schema has` <quotetype> `in their response)
- Merged streaming XSD to Quote XSD (only 1 line difference is `<cvol>` field.)
- Added options search (enums to build URL)

Can you update this on your maven repo so I can add this as maven dependencies to other maven projects? 

Also, ccook moved his project to gitlab so the link on your repo to conniption doesn't work anymore.

Let me know if you have questions.
Keith Nguyen

### CODE REVIEW

**Comment by xgp** [comment]
This is great. Thanks for doing all this work.

Is it possible to submit a request without all the formatting changes? It's really hard for me to see what actually changed versus just indentation in the diff.

**Comment by ecigar13** [comment]
Ok, let me try. 
Also, what IDE do you use? The indentation comes from my eclipse.

**Comment by xgp** [comment]
I just use Emacs, but you should be able to get the same formatting if you turn your IDE to use 4 spaces for indentation. It looks like you're using 2 tabs.

Also, if you split up the pull request into several chunks, it will be easier to review each one. It looks like you've got several commits that would each be a good individual pull request. Small batches are better than big ones for discussing changes and catching bugs! ;)

**Comment by ecigar13** [comment]
I'm sending pull requests. I can't separate the commits for each pull
request so let me know what you think.

*Keith Nguyen*

**Pull request closed without merging**
